window.ovaDashboardInventory = {
  visibleBrandKeys: [
    "dior",
    "armani",
    "lattafa",
    "kayali",
    "jeanpaulgaultier",
    "tomford",
    "xerjoff",
    "rarescents"
  ],
  featuredProducts: [
    "Diamond Emerald Soul 200ml",
    "Nude Coral Diamond",
    "Lahab - Hersh",
    "Khamrah Classic",
    "Eclaire",
    "Qissa Imperial Valley 200ml",
    "Imagination",
    "Tom Ford Tobacco Vanille",
    "Spicebomb Extreme",
    "Baccarat Rouge Master Box Original",
    "Burberry Her Box",
    "Si Red (Armani Si)",
    "Gucci Bloom",
    "Valentino Uomo Born In Roma Intense",
    "Prada Paradoxe Intense",
    "Stronger With You Intensely",
    "Jean Paul Gaultier Le Male Le Parfum",
    "Sauvage",
    "Bleu de Chanel Eau de Parfum",
    "Le Male Elixir",
    "Khamrah Qahwa",
    "Assaf Angel 200ml",
    "Assaf Pink Lady 200ml",
    "Diamond Pink Score 200ml"
  ],
  standaloneProducts: [
    "Wild Cold 200ml",
    "Assaf Angel 200ml",
    "Assaf Pink Lady 200ml",
    "Diamond Pink Score 200ml",
    "One & Only 200ml",
    "La Luna 200ml",
    "Issey Miyake",
    "Spanish Tobacco",
    "Arabian Tobacco",
    "Khamrah 40ml",
    "Acqua di Gio Eau de Toilette",
    "Lattafa His Confession",
    "Hugo Boss Bottled Elixir",
    "Versace Eros Eau de Toilette",
    "Versace Eros Flame",
    "Dolce & Gabbana The One Eau de Parfum",
    "Hudson Valley Perfume",
    "Baccarat Rouge 540 40ml",
    "Amira Al Arab",
    "Laverne Sense",
    "Carolina Herrera 212 VIP Rose",
    "Hugo Boss The Scent Elixir For Her",
    "Valentino Donna Born in Roma",
    "Elie Saab Girl of Now",
    "Paco Rabanne Olympea",
    "Victoria's Secret Bombshell",
    "Victoria's Secret Very Sexy",
    "Victoria's Secret Noir Tease"
  ],
  menProducts: [
    "Imagination",
    "Spicebomb Extreme",
    "Valentino Uomo Born In Roma Intense",
    "Jean Paul Gaultier Le Male Le Parfum",
    "Sauvage",
    "Bleu de Chanel Eau de Parfum",
    "Le Male Elixir",
    "Dior Homme Intense",
    "Stronger With You (Original)",
    "Stronger With You Absolutely",
    "Stronger With You Intensely",
    "Stronger With You Freeze",
    "Stronger With You Tobacco",
    "Asad",
    "Asad Bourbon",
    "Asad Zanzibar",
    "Ultra Male",
    "Scandal Pour Homme",
    "Tom Ford Noir",
    "Issey Miyake",
    "Acqua di Gio Eau de Toilette",
    "Lattafa His Confession",
    "Hugo Boss Bottled Elixir",
    "Versace Eros Eau de Toilette",
    "Versace Eros Flame",
    "Dolce & Gabbana The One Eau de Parfum"
  ],
  womenProducts: [
    "Eclaire",
    "Burberry Her Box",
    "Si Red (Armani Si)",
    "Gucci Bloom",
    "Prada Paradoxe Intense",
    "Hudson Valley Perfume",
    "Baccarat Rouge 540 40ml",
    "Amira Al Arab",
    "Lattafa His Confession",
    "Lattafa Her Confession",
    "Berry on Top",
    "Choco Overdose",
    "Cookie Crave",
    "Vanilla Freak",
    "Mallow Madness",
    "Laverne Sense",
    "Carolina Herrera 212 VIP Rose",
    "Hugo Boss The Scent Elixir For Her",
    "Valentino Donna Born in Roma",
    "Elie Saab Girl of Now",
    "Paco Rabanne Olympea",
    "Victoria's Secret Bombshell",
    "Victoria's Secret Very Sexy",
    "Victoria's Secret Noir Tease",
    "J'adore",
    "Miss Dior Blooming Bouquet",
    "Hypnotic Poison",
    "Armani My Way Eau de Parfum",
    "Armani Si Passione Eau de Parfum",
    "Armani Si Eau de Parfum",
    "Armani Si (Original)",
    "Iman",
    "Haya",
    "Sakeena",
    "Yara",
    "Yara Candy",
    "Yara Elixir",
    "Yara Moi",
    "La Luna 200ml",
    "Vanilla Candy Rock Sugar | 42",
    "Boujee Marshmallow | 81",
    "Pistachio Gelato | 33",
    "Divine",
    "La Belle Le Parfum",
    "Scandal (Women)",
    "Scandal Absolu",
    "Scandal Le Parfum"
  ],
  unisexProducts: [
    "Diamond Emerald Soul 200ml",
    "Nude Coral Diamond",
    "Lahab - Hersh",
    "Khamrah Classic",
    "Wild Cold 200ml",
    "Assaf Angel 200ml",
    "Assaf Pink Lady 200ml",
    "Diamond Pink Score 200ml",
    "One & Only 200ml",
    "Qissa Imperial Valley 200ml",
    "Imagination",
    "Tom Ford Tobacco Vanille",
    "Baccarat Rouge Master Box Original",
    "Khamrah Qahwa",
    "Oud Ispahan",
    "Ameer Al Oud",
    "Oud Mood",
    "Khamrah Dukhan",
    "Lattafa Musamam",
    "Lattafa Musamam White",
    "Vanilla | 28",
    "Eden Juicy Apple | 01",
    "Cafe Oud | 19",
    "Oudgasm Smoky Oud | 07",
    "Vanilla Oud | 36",
    "Xerjoff Naxos",
    "Xerjoff Alexandria II",
    "Xerjoff Torino21",
    "Musk Powder",
    "Musk Al Khas",
    "Spanish Tobacco",
    "Arabian Tobacco",
    "Black Carbon",
    "Tom Ford Ombre Leather",
    "Tom Ford Black Orchid",
    "Khamrah 40ml"
  ]
};
