[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/product-sitemap.xml"
  to = "/.netlify/functions/product-sitemap"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
